package HopfieldModel;
//
// Hopfield Network
//

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

 public class HopfieldOut extends NslOutModule /*(int MAXSIZE, int MAXSIZE2)*/ {

    public NslDinDouble0 energy ; /*()*/
    public NslDinDouble2 output ; /*(MAXSIZE,MAXSIZE)*/
    
    public  void initModule() {
        nslAddAreaCanvas(output,-1,1);
        nslAddTemporalCanvas(energy,-MAXSIZE2,MAXSIZE2);
    }
    
	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	/* constructor and related methods */
	/* nsl declarations */
	int MAXSIZE;
	int MAXSIZE2;

	 /*GENERIC CONSTRUCTOR:   */
	 public HopfieldOut(String nslName, NslModule nslParent,int MAXSIZE, int MAXSIZE2) {
		super(nslName, nslParent);
		this.MAXSIZE = MAXSIZE;
		this.MAXSIZE2 = MAXSIZE2;
		initSys();
		makeInst(nslName, nslParent,MAXSIZE, MAXSIZE2);
	}
	public void makeInst(String nslName, NslModule nslParent,int MAXSIZE,int MAXSIZE2){ 
	 energy=new NslDinDouble0 ("energy",this); //NSLDECLS 
	 output=new NslDinDouble2 ("output",this,MAXSIZE,MAXSIZE); //NSLDECLS 
	}
	/* end of automatic declaration statements */
}
