package HopfieldModel;
//
// Hopfield Network
//


 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

 public class HopfieldIn extends NslInModule /*(int MAXSIZE)*/ {

    public NslDoutDouble2 input ; /*(MAXSIZE,MAXSIZE)*/
    
    public  void initModule() {
    	input.nslSetBuffering(false);
    	input.set(-(1));
        addInputImageCanvas(input,-1,1);
        addPanel("control");
        addButton("clear","Clear image","control");
    }
       
    public  void clearPushed() {
    	input.set(-(1));
    	nslUpdateBuffers();
    }
	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	/* constructor and related methods */
	/* nsl declarations */
	int MAXSIZE;

	 /*GENERIC CONSTRUCTOR:   */
	 public HopfieldIn(String nslName, NslModule nslParent,int MAXSIZE) {
		super(nslName, nslParent);
		this.MAXSIZE = MAXSIZE;
		initSys();
		makeInst(nslName, nslParent,MAXSIZE);
	}
	public void makeInst(String nslName, NslModule nslParent,int MAXSIZE){ 
	 input=new NslDoutDouble2 ("input",this,MAXSIZE,MAXSIZE); //NSLDECLS 
	}
	/* end of automatic declaration statements */
}
