package BackPropModel;

/* Copyright 1999 University of Southern California Brain Lab */
/* email nsl@java.usc.edu */

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

 public class BPDisplayResult extends NslOutModule /*(int inSize, int outSize)*/ {

    private NslFloat1 in ; /*(inSize)*/
    private NslFloat1 outTemp ; /*(outSize)*/	
    private NslFloat0 out ; /*()*/	

    public  void initModule() {
	nslAddAreaCanvas(in,0,1);
	nslAddAreaCanvas(out,0,1);		
    }

    public  void simTrain() {
	simRun();
    }

    public  void simRun() {
	in.set((NslFloat1)(nslGetValue("backPropModel.forward.p"))) /*rule 114 */;
	outTemp.set((NslFloat1)(nslGetValue("backPropModel.forward.yo"))) /*rule 114 */;
	out.set((outTemp).get(0));
    }

	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	/* constructor and related methods */
	/* nsl declarations */
	int inSize;
	int outSize;

	 /*GENERIC CONSTRUCTOR:   */
	 public BPDisplayResult(String nslName, NslModule nslParent,int inSize, int outSize) {
		super(nslName, nslParent);
		this.inSize = inSize;
		this.outSize = outSize;
		initSys();
		makeInst(nslName, nslParent,inSize, outSize);
	}
	public void makeInst(String nslName, NslModule nslParent,int inSize,int outSize){ 
	 in=new NslFloat1 ("in",this,inSize); //NSLDECLS 
	 outTemp=new NslFloat1 ("outTemp",this,outSize); //NSLDECLS 
	 out=new NslFloat0 ("out",this); //NSLDECLS 
	}
	/* end of automatic declaration statements */
}
