package BackPropModel;

/* Copyright 1999 University of Southern California Brain Lab */
/* email nsl@java.usc.edu */

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

// changed "extends NSLModule to NslOutModule" - AW Aug 2015
 public class TrainManager extends NslModule /*(int nPats,int inSize,int outSize)*/  {                   
        public NslDoutFloat1 p ; /*(inSize)*/
        public NslDoutFloat1 t ; /*(outSize)*/

        private NslFloat2 patterns ; /*(nPats, inSize)*/
        private NslFloat2 outputs ; /*(nPats, outSize)*/
        
public  void simTrain() {
             int pat = system.getFinishedCycles(); 
            p.set(NslGetRow.eval(patterns,pat)) /* rule 108 */;
	    t.set(NslGetRow.eval(outputs,pat)) /* rule 108 */; 
	}
	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	/* constructor and related methods */
	/* nsl declarations */
	int nPats;
	int inSize;
	int outSize;

	 /*GENERIC CONSTRUCTOR:   */
	 public TrainManager(String nslName, NslModule nslParent,int nPats, int inSize, int outSize) {
		super(nslName, nslParent);
		this.nPats = nPats;
		this.inSize = inSize;
		this.outSize = outSize;
		initSys();
		makeInst(nslName, nslParent,nPats, inSize, outSize);
	}
	public void makeInst(String nslName, NslModule nslParent,int nPats,int inSize,int outSize){ 
	 p=new NslDoutFloat1 ("p",this,inSize); //NSLDECLS 
	 t=new NslDoutFloat1 ("t",this,outSize); //NSLDECLS 
	 patterns=new NslFloat2 ("patterns",this,nPats,inSize); //NSLDECLS 
	 outputs=new NslFloat2 ("outputs",this,nPats,outSize); //NSLDECLS 
         
	}
	/* end of automatic declaration statements */
}
