package MaxSelectorModel;

 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 

public class MaxSelectorOutput/*(int size)*/  extends NslOutModule /*()*/ {

    public NslDinDouble1 s_out ; /*(size)*/
    public NslDinDouble1 uf ; /*(size)*/
    private NslDouble1 up ; /*(size)*/
    private  boolean worked= false;
    
    public  void initModule() {
	up.nslSetAccess('W');
    	nslAddAreaCanvas(s_out,0,1);
    	nslAddTemporalCanvas(up,-2.5,2.5);
    	nslAddAreaCanvas(uf,0,1);
    }
    
    public  void simRun() {
	// slow
	//up=(NslDouble1)nslGetValue("maxSelectorModel.maxselector.u1.up");
	//fast
	worked=nslSetValue(up,"maxSelectorModel.maxselector.u1.up")/* rule 102*/;
    }

	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	/* constructor and related methods */
	/* nsl declarations */
	int size;

	 /*GENERIC CONSTRUCTOR:   */
	 public MaxSelectorOutput(String nslName, NslModule nslParent,int size) {
		super(nslName, nslParent);
		this.size = size;
		initSys();
		makeInst(nslName, nslParent,size);
	}
	public void makeInst(String nslName, NslModule nslParent,int size){ 
	 s_out=new NslDinDouble1 ("s_out",this,size); //NSLDECLS 
	 uf=new NslDinDouble1 ("uf",this,size); //NSLDECLS 
	 up=new NslDouble1 ("up",this,size); //NSLDECLS 
	}
	/* end of automatic declaration statements */
}
