package MaxSelectorModel;
//
// MaxSelector for MaxSelectorModel
//
////////////////////////////////////////////////////////////
 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 


public class MaxSelector/*(int size)*/  extends NslModule/*()*/ {

public NslDinDouble1 in ; /*(size)*/
public NslDoutDouble1 out ; /*(size)*/

private Ulayer u1 ; /*(size)*/  //change later
private Vlayer v1 ; /*()*/                   

	public  void makeConn() {
            nslConnect(this.in, u1.s_in); 
	    nslConnect(u1.uf, v1.u_in); 
	    nslConnect(v1.vf, u1.v_in); 
	    nslConnect(u1.uf,this.out);
	}

	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	/* constructor and related methods */
	/* nsl declarations */
	int size;

	 /*GENERIC CONSTRUCTOR  */
	 public MaxSelector(String nslName, NslModule nslParent,int size) {
		super(nslName, nslParent);
		this.size = size;
		initSys();
		makeInst(nslName, nslParent,size);
	}
	public void makeInst(String nslName, NslModule nslParent,int size){ 
	 in=new NslDinDouble1 ("in",this,size); //NSLDECLS 
	 out=new NslDoutDouble1 ("out",this,size); //NSLDECLS 
	 u1=new Ulayer ("u1",this,size); //NSLDECLS 
	 v1=new Vlayer ("v1",this); //NSLDECLS 
	}
	/* end of automatic declaration statements */
}
