package MaxSelectorModel;
//
// MaxSelectorStimulus
//
//////////////////////////////////////////////////////////////////////

 import hierarchyList.treeTraversal;
 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 
import xmlUtility.xmlParser;
 

public class MaxSelectorStimulus/*(int size)*/  extends NslModule/*()*/ {

public NslDoutDouble1 s_out ; /*(size)*/


	public  void initRun() {
                //Set the values of s_out directly in the xml do not change values in the parser.
                xmlParser parseStim = new xmlParser();
                parseStim.setStimulus(s_out);
                
                
//                treeTraversal print = new treeTraversal();
//                print.printHierarchy(); 
                
                                
                                
	}
	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	/* constructor and related methods */
	/* nsl declarations */
	int size;

	 /*GENERIC CONSTRUCTOR:   */
	 public MaxSelectorStimulus(String nslName, NslModule nslParent,int size) {
		super(nslName, nslParent);
		this.size = size;
		initSys();
		makeInst(nslName, nslParent,size);
	}
	public void makeInst(String nslName, NslModule nslParent,int size){ 
	 s_out=new NslDoutDouble1 ("s_out",this,size); //NSLDECLS 
	}
	/* end of automatic declaration statements */
}
