package MaxSelectorModel;
//
// MaxSelectorStimulus
//
//////////////////////////////////////////////////////////////////////

 import hierarchyList.treeTraversal;
 import nslj.src.system.*; 
 import nslj.src.cmd.*; 
 import nslj.src.lang.*; 
 import nslj.src.math.*; 
 import nslj.src.display.*; 
 

public class MaxSelectorStimulus/*(int size)*/  extends NslModule/*()*/ {

public NslDoutDouble1 s_out ; /*(size)*/


	public  void initRun() {
		s_out.set(0);
		(s_out).set(1,0.5);
		(s_out).set(3,1.0);
                (s_out).set(7,0.5);
                
                                
                                
	}
	/* nslInitTempModule inserted by NPP */
public void nslInitTempModule() {
	/* Instantiation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic instantiation statements */
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempRun inserted by NPP */
public void nslInitTempRun() {
	/* Intialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* nslInitTempTrain inserted by NPP */
public void nslInitTempTrain() {
	/* Initialisation statements generated by NslPreProcessor */
	/* temporary variables */
	/* end of automatic intialisation statements */
}

	/* Declaration statements generated by NslPreProcessor */
	/* makeinst() declared variables */
	/* temporary variables */
	/* constructor and related methods */
	/* nsl declarations */
	int size;

	 /*GENERIC CONSTRUCTOR:   */
	 public MaxSelectorStimulus(String nslName, NslModule nslParent,int size) {
		super(nslName, nslParent);
		this.size = size;
		initSys();
		makeInst(nslName, nslParent,size);
	}
	public void makeInst(String nslName, NslModule nslParent,int size){ 
	 s_out=new NslDoutDouble1 ("s_out",this,size); //NSLDECLS 
	}
	/* end of automatic declaration statements */
}
